#!/bin/bash
set -e

echo "=========================================="
echo "Co-Intelligence GCP Deployment"
echo "=========================================="

# Check prerequisites
command -v gcloud >/dev/null 2>&1 || { echo "gcloud CLI required"; exit 1; }
command -v terraform >/dev/null 2>&1 || { echo "terraform required"; exit 1; }
command -v kubectl >/dev/null 2>&1 || { echo "kubectl required"; exit 1; }
command -v docker >/dev/null 2>&1 || { echo "docker required"; exit 1; }

TERRAFORM_DIR="infrastructure/gcp"

# Check if Terraform has been applied
if [ ! -f "$TERRAFORM_DIR/terraform.tfstate" ]; then
    echo "Error: Terraform state not found. Run 'terraform apply' first:"
    echo "  cd $TERRAFORM_DIR && terraform init && terraform apply"
    exit 1
fi

echo "Fetching Terraform outputs..."
cd $TERRAFORM_DIR

PROJECT_ID=$(terraform output -raw project_id)
REGION=$(terraform output -raw region)
GKE_CLUSTER=$(terraform output -raw gke_cluster_name)
GKE_ZONE=$(terraform output -raw gke_zone)
DB_HOST=$(terraform output -raw db_host)
DB_NAME=$(terraform output -raw db_name)
DB_USERNAME=$(terraform output -raw db_username)
DB_PASSWORD=$(terraform output -raw db_password)
SECRET_KEY=$(terraform output -raw secret_key)
BACKEND_REGISTRY=$(terraform output -raw backend_registry)
FRONTEND_REGISTRY=$(terraform output -raw frontend_registry)
BUCKET_NAME=$(terraform output -raw bucket_name)

cd ../..

echo "✓ Terraform outputs retrieved"

# Load user-provided API keys from .env.gcp if exists
GEMINI_API_KEY=""
GROQ_API_KEY=""
AWS_ACCESS_KEY_ID=""
AWS_SECRET_ACCESS_KEY=""
AWS_REGION="us-east-1"

if [ -f ".env.gcp" ]; then
    echo "Loading API keys from .env.gcp..."
    source <(grep -E '^(GEMINI_API_KEY|GROQ_API_KEY|AWS_ACCESS_KEY_ID|AWS_SECRET_ACCESS_KEY|AWS_REGION)=' .env.gcp)
fi

# Prompt for missing required keys
if [ -z "$GEMINI_API_KEY" ] || [ "$GEMINI_API_KEY" = "your-gemini-api-key" ]; then
    read -p "Enter GEMINI_API_KEY (or press Enter to skip AI features): " GEMINI_API_KEY
    GEMINI_API_KEY=${GEMINI_API_KEY:-"placeholder"}
fi

if [ -z "$GROQ_API_KEY" ] || [ "$GROQ_API_KEY" = "your-groq-api-key" ]; then
    read -p "Enter GROQ_API_KEY (or press Enter to skip): " GROQ_API_KEY
    GROQ_API_KEY=${GROQ_API_KEY:-"placeholder"}
fi

# Generate .env.gcp with all values
echo "Generating .env.gcp..."
cat > .env.gcp << EOF
# GCP Configuration - Auto-generated by deploy-gcp.sh
GCP_PROJECT_ID=$PROJECT_ID
GCP_REGION=$REGION

# Database
DATABASE_URL=postgres://$DB_USERNAME:$DB_PASSWORD@$DB_HOST:5432/$DB_NAME

# Storage
GCS_BUCKET=$BUCKET_NAME

# App
SECRET_KEY=$SECRET_KEY

# AI API Keys (USER PROVIDED)
GEMINI_API_KEY=$GEMINI_API_KEY
GROQ_API_KEY=$GROQ_API_KEY

# AWS Credentials (for Bedrock)
AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
AWS_REGION=$AWS_REGION

# Registry
BACKEND_IMAGE=$BACKEND_REGISTRY/backend:latest
FRONTEND_IMAGE=$FRONTEND_REGISTRY/frontend:latest
EOF
echo "✓ .env.gcp generated"

# Configure Docker for Artifact Registry
echo "Configuring Docker for Artifact Registry..."
gcloud auth configure-docker $REGION-docker.pkg.dev --quiet
echo "✓ Docker configured"

# Build and push images
echo "Building and pushing backend image..."
docker build -t $BACKEND_REGISTRY/backend:latest ./backend
docker push $BACKEND_REGISTRY/backend:latest
echo "✓ Backend image pushed"

echo "Building and pushing frontend image..."
docker build -t $FRONTEND_REGISTRY/frontend:latest ./frontend
docker push $FRONTEND_REGISTRY/frontend:latest
echo "✓ Frontend image pushed"

# Configure kubectl for GKE
echo "Configuring kubectl for GKE..."
gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $PROJECT_ID
echo "✓ kubectl configured"

# Create namespace if not exists
kubectl create namespace co-intelligence --dry-run=client -o yaml | kubectl apply -f -

# Create K8s secrets with all env vars
echo "Creating Kubernetes secrets..."
kubectl delete secret app-secrets -n co-intelligence 2>/dev/null || true
kubectl create secret generic app-secrets \
    --namespace co-intelligence \
    --from-literal=DATABASE_URL="postgres://$DB_USERNAME:$DB_PASSWORD@$DB_HOST:5432/$DB_NAME" \
    --from-literal=SECRET_KEY="$SECRET_KEY" \
    --from-literal=GCS_BUCKET="$BUCKET_NAME" \
    --from-literal=GEMINI_API_KEY="$GEMINI_API_KEY" \
    --from-literal=GROQ_API_KEY="$GROQ_API_KEY" \
    --from-literal=AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID:-placeholder}" \
    --from-literal=AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY:-placeholder}" \
    --from-literal=AWS_REGION="$AWS_REGION"
echo "✓ Secrets created"

# Generate GCP-specific K8s manifests
echo "Generating GCP Kubernetes manifests..."
mkdir -p k8s-gcp

cat > k8s-gcp/backend.yaml << EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: co-intelligence
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: $BACKEND_REGISTRY/backend:latest
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: app-secrets
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: co-intelligence
spec:
  selector:
    app: backend
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
EOF

cat > k8s-gcp/frontend.yaml << EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: co-intelligence
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: $FRONTEND_REGISTRY/frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_API_URL
          value: "http://backend:8000"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: co-intelligence
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 3000
  type: LoadBalancer
EOF

cat > k8s-gcp/hpa.yaml << EOF
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
  namespace: co-intelligence
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
  namespace: co-intelligence
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
EOF

echo "✓ K8s manifests generated"

# Apply K8s manifests
echo "Applying Kubernetes manifests..."
kubectl apply -f k8s-gcp/
echo "✓ Manifests applied"

# Wait for LoadBalancer IP
echo "Waiting for LoadBalancer external IP..."
for i in {1..30}; do
    EXTERNAL_IP=$(kubectl get svc frontend -n co-intelligence -o jsonpath='{.status.loadBalancer.ingress[0].ip}' 2>/dev/null)
    if [ -n "$EXTERNAL_IP" ]; then
        break
    fi
    echo "  Waiting... ($i/30)"
    sleep 10
done

echo ""
echo "=========================================="
echo "Deployment Complete!"
echo "=========================================="
echo ""
echo "Frontend URL: http://$EXTERNAL_IP"
echo "Config saved: .env.gcp"
echo ""
echo "Useful commands:"
echo "  kubectl get pods -n co-intelligence"
echo "  kubectl logs -f deployment/backend -n co-intelligence"
echo "  kubectl logs -f deployment/frontend -n co-intelligence"
